abstract final class AppPaths {
  static const home = '/';
  static const news = '/news';
  static const newsEdit = 'edit';
  static const venues = '/venues';
  static const venueEdit = 'edit';
  static const speakers = '/speakers';
  static const speakerEdit = 'edit';
  static const staff = '/staff';
  static const staffMemberEdit = 'edit';
  static const timeline = '/timeline';
  static const timelineEventEdit = 'edit';
  static const sessions = '/sessions';
  static const sessionEdit = 'edit';
  static const sponsors = '/sponsors';
  static const sponsorEdit = 'edit';
  static const quiz = '/quiz';
  static const quizConsole = ':eventId';
  static const quizQuestionEdit = 'questions/edit';
}
