name: Deploy website to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - apps/website/**
      - .github/workflows/deploy_website.yaml
  workflow_dispatch:

concurrency:
  group: deploy-website
  cancel-in-progress: false

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - id: flutter-version
        run: echo "version=$(jq -r .flutter .fvmrc)" >> "$GITHUB_OUTPUT"

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          flutter-version: ${{ steps.flutter-version.outputs.version }}
          channel: stable
          cache: true

      - run: dart pub get

      - working-directory: apps/website
        run: dart run jaspr_cli:jaspr build

      - uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: apps/website
          command: deploy
